version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipes"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET: ${JWT_SECRET}
        NODE_ENV: production
        SKIP_AUTH: ${SKIP_AUTH}
        REVALIDATE_SECRET: ${REVALIDATE_SECRET}
        WEBHOOK_SECRET: ${WEBHOOK_SECRET}
        ADMIN_SECRET: ${ADMIN_SECRET}
        STATIC_EXPORT: ${STATIC_EXPORT}
        MOCK: ${MOCK}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads

volumes:
  postgres_data:
  uploads:
